version: "3"
services:
  website:
    image: "observatorio/ui-website"
    container_name: "website"
    build: .
    command: npm run dev
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    volumes:
      - ./pages:/app/pages/
      - ./components:/app/components/
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
