version: "3"
services:
  website:
    image: "observatorio/ui-website"
    container_name: "website"
    build: .
    command: npm run dev
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src/
      - ./public:/app/public/
      - ./next.config.json:/app/next.config.json
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./.eslintrc:/app/.eslintrc
